
init-packages:
	npm i

start:
	simpleTextIndexing -in /Users/andrey/OTUS/Projects/otus/nodeJsDeveloper/simpleTextIndexing/resources/index.txt -out /Users/andrey/OTUS/Projects/otus/nodeJsDeveloper/simpleTextIndexing/resources/out-index.txt

