
init-packages:
	npm i

lint:
	npx eslint . --fix

start-json:
	tree -s json -p /Users/andrey/OTUS/Projects/otus/nodeJsDeveloper/tree/resources/index.json -d 10

start-directory:
	tree -s directory -p /Users/andrey/OTUS/Projects/otus/nodeJsDeveloper/tree -d 2

